module.exports = {
  // ipc 相关
  GET_ARTICLE_LIST: "article:getList",
  SEND_ARTICLE_LIST: "article:sendList",
  GET_ARTICLE_CONTENT: "article:getContent",
  SEND_ARTICLE_CONTENT: "article:sendContent",
  SAVE_ARTICLE: "article:save",
  SAVED_ARTICLE: "article:saved",
  MODIFY_ARTICLE_TITLE:"article:modifyTitle",
  MODIFIED_ARTICLE_TITLE:"article:modifiedTitle",
  // action 相关
  ARTICLELIST: "ARTICLELIST",
  ARTICLECONTENT:"ARTICLECONTENT",
  MODIFYRENDERCONTENT:"MODIFYRENDERCONTENT",
  MODIFY_TITLE:"MODIFY_TITLE",
  COLLAPSE_SIDER: "COLLAPSE_SIDER",
  TITTLE_TOGGLE:"TITTLE_TOGGLE",
  SAVESUCCESSED:"SAVE_SUCCESSED",
};
